create TABLE country (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255),
        continent VARCHAR(255)
);

-- Author
CREATE TABLE author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255),
                        surname VARCHAR(255),
                        country_id BIGINT REFERENCES country ON DELETE SET NULL
);

-- Book
CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255),
                      category VARCHAR(50),
                      author_id BIGINT REFERENCES author ON DELETE SET NULL,
                      available_copies INT
);

-- User
CREATE TABLE shop_users (
                            username VARCHAR(255) PRIMARY KEY,
                            password VARCHAR(255),
                            name VARCHAR(255),
                            surname VARCHAR(255),
                            is_account_non_expired BOOLEAN DEFAULT TRUE,
                            is_account_non_locked BOOLEAN DEFAULT TRUE,
                            is_credentials_non_expired BOOLEAN DEFAULT TRUE,
                            is_enabled BOOLEAN DEFAULT TRUE,
                            role VARCHAR(50)
);

-- Wishlist
CREATE TABLE wishlist (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_username VARCHAR(255) REFERENCES shop_users ON DELETE CASCADE
);

-- Wishlist - Books (many-to-many)
CREATE TABLE wishlist_books (
                                wishlist_id BIGINT REFERENCES wishlist ON DELETE CASCADE,
                                books_id BIGINT REFERENCES book ON DELETE CASCADE,
                                PRIMARY KEY (wishlist_id, books_id)
);

-- UserBooks
CREATE TABLE user_books (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            book_id BIGINT REFERENCES book ON DELETE CASCADE,
                            username VARCHAR(255) REFERENCES shop_users ON DELETE CASCADE
);

-- Indexes (опционално, но препорачливо)
CREATE INDEX idx_user_role ON shop_users(role);
CREATE INDEX idx_user_username ON shop_users(username);
CREATE INDEX idx_book_author ON book(author_id);
CREATE INDEX idx_book_category ON book(category);
CREATE INDEX idx_user_books_username ON user_books(username);
CREATE INDEX idx_wishlist_user ON wishlist(user_username);

-- INSERT countries
INSERT INTO country (name,continent) VALUES
                                         ( 'North Macedonia','Europe'),
                                         ('USA','America'),
                                         ('Germany','Europe');

-- INSERT authors
INSERT INTO author ( name, surname, country_id) VALUES
                                                    ( 'Petre', 'Andreevski', 1),
                                                    ('Stephen', 'King', 2),
                                                    ('Hermann', 'Hesse', 3);

-- INSERT books
INSERT INTO book ( name, category ,author_id, available_copies) VALUES
                                                                    ( 'Pirej', 'NOVEL', 1, 10),
                                                                    ( 'It', 'DRAMA', 2, 20),
                                                                    ( 'Steppenwolf', 'FANTASY', 3, 30);

